# -*- coding: utf-8 -*-
"""Dummy cloud.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KfFp6mbT5PDtj0pAX0EDGyPorYgbJych
"""

!pip install Pyrebase
import pyrebase
firebaseConfig = {"apiKey": "AIzaSyBtvYVGOK_mABhU41riPue9cQicjnWvoIU",
  "authDomain": "driverassisting.firebaseapp.com",
  "databaseURL": "https://driverassisting-default-rtdb.firebaseio.com",
  "projectId": "driverassisting",
  "storageBucket": "driverassisting.appspot.com",
  "messagingSenderId": "939478415947",
  "appId": "1:939478415947:web:0bbfb008e8b8e20f5aabce",
  "measurementId": "G-1N5LZWKHHZ"}

firebase = pyrebase.initialize_app(firebaseConfig)
db = firebase.database()

data={"current_speed":"100","current_acceleration":"1.5","idling_duration":"35","number_of_brakes":"4","obstacle_present":"True","source_location":(11.1039,76.9629),"Dest_location":(11.0238,76.9452)}

db.child("Sensor_Out").set(data)